# https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# From https://github.com/rollup/plugins/blob/master/.github/workflows/validate.yml

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['18', '16', '14']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        run: npm install pnpm -g

      - name: Sanity Check
        run: |
          echo branch `git branch --show-current`;
          echo node `node --version`;
          echo yarn `pnpm --version`

      - name: pnpm install
        run: pnpm install

      # pnpm audit isn't as robust as it needs to be atm
      # - name: Audit Dependencies
      #   run: pnpm security

      - run: pnpm run build --if-present
      - run: pnpm test
